openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub v3 REST API
  description: GitHub's v3 REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: api.github.com
servers:
- url: https://api.github.com
components:
  schemas:
    network-configuration:
      title: Hosted compute network configuration
      description: A hosted compute network configuration.
      type: object
      properties:
        id:
          description: The unique identifier of the network configuration.
          type: string
          example: 123ABC456DEF789
        name:
          description: The name of the network configuration.
          type: string
          example: my-network-configuration
        compute_service:
          description: The hosted compute service the network configuration supports.
          type: string
          enum:
          - none
          - actions
          - codespaces
        network_settings_ids:
          description: The unique identifier of each network settings in the configuration.
          type: array
          items:
            type: string
          example: 123ABC456DEF789
        created_on:
          description: The time at which the network configuration was created, in ISO 8601 format.
          type: string
          format: date-time
          example: '2024-04-26T11:31:07Z'
          nullable: true
      required:
      - id
      - name
      - created_on
    network-settings:
      title: Hosted compute network settings resource
      description: A hosted compute network settings resource.
      type: object
      properties:
        id:
          description: The unique identifier of the network settings resource.
          type: string
          example: 220F78DACB92BBFBC5E6F22DE1CCF52309D
        network_configuration_id:
          description: The identifier of the network configuration that is using this settings resource.
          type: string
          example: 934E208B3EE0BD60CF5F752C426BFB53562
        name:
          description: The name of the network settings resource.
          type: string
          example: my-network-settings
        subnet_id:
          description: The subnet this network settings resource is configured for.
          type: string
          example: /subscriptions/14839728-3ad9-43ab-bd2b-fa6ad0f75e2a/resourceGroups/my-rg/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/my-subnet
        region:
          description: The location of the subnet this network settings resource is configured for.
          type: string
          example: eastus
      required:
      - id
      - name
      - subnet_id
      - region
  examples:
    network-configurations-paginated:
      value:
        total_count: 2
        network_configurations:
        - id: 123456789ABCDEF
          name: My network configuration
          compute_service: actions
          network_settings_ids:
          - 23456789ABDCEF1
          - 3456789ABDCEF12
          created_on: '2022-10-09T23:39:01Z'
        - id: 456789ABDCEF123
          name: My other configuration
          compute_service: none
          network_settings_ids:
          - 56789ABDCEF1234
          - 6789ABDCEF12345
          created_on: '2023-04-26T15:23:37Z'
    network-configuration:
      value:
        id: 123456789ABCDEF
        name: My network configuration
        compute_service: actions
        network_settings_ids:
        - 23456789ABDCEF1
        - 3456789ABDCEF12
        created_on: '2022-10-09T23:39:01Z'
    network-settings:
      value:
        id: 220F78DACB92BBFBC5E6F22DE1CCF52309D
        network_configuration_id: 934E208B3EE0BD60CF5F752C426BFB53562
        name: my_network_settings
        subnet_id: /subscriptions/14839728-3ad9-43ab-bd2b-fa6ad0f75e2a/resourceGroups/my-rg/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/my-subnet
        region: eastus
  parameters:
    per-page:
      name: per_page
      description: The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 30
    page:
      name: page
      description: The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 1
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    network-configuration-id:
      name: network_configuration_id
      description: Unique identifier of the hosted compute network configuration.
      in: path
      required: true
      schema:
        type: string
    network-settings-id:
      name: network_settings_id
      description: Unique identifier of the hosted compute network settings.
      in: path
      required: true
      schema:
        type: string
  headers:
    link:
      example: <https://api.github.com/resource?page=2>; rel="next", <https://api.github.com/resource?page=5>; rel="last"
      schema:
        type: string
security: []
tags:
- name: hosted-compute
  description: Manage hosted compute networking resources.
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
paths:
  /orgs/{org}/settings/network-configurations:
    get:
      summary: List hosted compute network configurations for an organization
      description: 'Lists all hosted compute network configurations configured in an organization.


        OAuth app tokens and personal access tokens (classic) need the `read:network_configurations` scope to use this endpoint.'
      tags:
      - hosted-compute
      operationId: hosted-compute/list-network-configurations-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/orgs/network-configurations#list-hosted-compute-network-configurations-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      - $ref: '#/components/parameters/per-page'
      - $ref: '#/components/parameters/page'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - network_configurations
                properties:
                  total_count:
                    type: integer
                  network_configurations:
                    type: array
                    items:
                      $ref: '#/components/schemas/network-configuration'
              examples:
                default:
                  $ref: '#/components/examples/network-configurations-paginated'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: orgs
        subcategory: network-configurations
    post:
      summary: Create a hosted compute network configuration for an organization
      description: 'Creates a hosted compute network configuration for an organization.


        OAuth app tokens and personal access tokens (classic) need the `write:network_configurations` scope to use this endpoint.'
      tags:
      - hosted-compute
      operationId: hosted-compute/create-network-configuration-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/orgs/network-configurations#create-a-hosted-compute-network-configuration-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Name of the network configuration. Must be between 1 and 100 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
                  type: string
                compute_service:
                  description: The hosted compute service to use for the network configuration.
                  type: string
                  enum:
                  - none
                  - actions
                network_settings_ids:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: The identifier of the network settings to use for the network configuration. Exactly one network settings must be specified.
                  items:
                    type: string
              required:
              - name
              - network_settings_ids
            examples:
              default:
                value:
                  name: my-network-configuration
                  network_settings_ids:
                  - 23456789ABDCEF1
                  compute_service: actions
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/network-configuration'
              examples:
                default:
                  $ref: '#/components/examples/network-configuration'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: orgs
        subcategory: network-configurations
  /orgs/{org}/settings/network-configurations/{network_configuration_id}:
    get:
      summary: Get a hosted compute network configuration for an organization
      description: 'Gets a hosted compute network configuration configured in an organization.


        OAuth app tokens and personal access tokens (classic) need the `read:network_configurations` scope to use this endpoint.'
      tags:
      - hosted-compute
      operationId: hosted-compute/get-network-configuration-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/orgs/network-configurations#get-a-hosted-compute-network-configuration-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      - $ref: '#/components/parameters/network-configuration-id'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/network-configuration'
              examples:
                default:
                  $ref: '#/components/examples/network-configuration'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: orgs
        subcategory: network-configurations
    patch:
      summary: Update a hosted compute network configuration for an organization
      description: 'Updates a hosted compute network configuration for an organization.


        OAuth app tokens and personal access tokens (classic) need the `write:network_configurations` scope to use this endpoint.'
      tags:
      - hosted-compute
      operationId: hosted-compute/update-network-configuration-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/orgs/network-configurations#update-a-hosted-compute-network-configuration-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      - $ref: '#/components/parameters/network-configuration-id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Name of the network configuration. Must be between 1 and 100 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
                  type: string
                compute_service:
                  description: The hosted compute service to use for the network configuration.
                  type: string
                  enum:
                  - none
                  - actions
                network_settings_ids:
                  type: array
                  minItems: 0
                  maxItems: 1
                  description: The identifier of the network settings to use for the network configuration. Exactly one network settings must be specified.
                  items:
                    type: string
            examples:
              default:
                value:
                  name: my-network-configuration
                  network_settings_ids:
                  - 23456789ABDCEF1
                  compute_service: actions
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/network-configuration'
              examples:
                default:
                  $ref: '#/components/examples/network-configuration'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: orgs
        subcategory: network-configurations
    delete:
      summary: Delete a hosted compute network configuration from an organization
      description: 'Deletes a hosted compute network configuration from an organization.


        OAuth app tokens and personal access tokens (classic) need the `write:network_configurations` scope to use this endpoint.'
      tags:
      - hosted-compute
      operationId: hosted-compute/delete-network-configuration-from-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/orgs/network-configurations#delete-a-hosted-compute-network-configuration-from-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      - $ref: '#/components/parameters/network-configuration-id'
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: orgs
        subcategory: network-configurations
  /orgs/{org}/settings/network-settings/{network_settings_id}:
    get:
      summary: Get a hosted compute network settings resource for an organization
      description: 'Gets a hosted compute network settings resource configured for an organization.


        OAuth app tokens and personal access tokens (classic) need the `read:network_configurations` scope to use this endpoint.'
      tags:
      - hosted-compute
      operationId: hosted-compute/get-network-settings-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/orgs/network-configurations#get-a-hosted-compute-network-settings-resource-for-an-organization
      parameters:
      - $ref: '#/components/parameters/org'
      - $ref: '#/components/parameters/network-settings-id'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/network-settings'
              examples:
                default:
                  $ref: '#/components/examples/network-settings'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: orgs
        subcategory: network-configurations
